# render.yaml
services:
  - type: web
    name: techcampus
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        fromSecret: SECRET_KEY
      - key: DB_NAME
        fromSecret: DB_NAME
      - key: DB_USER
        fromSecret: DB_USER
      - key: DB_PASSWORD
        fromSecret: DB_PASSWORD
      - key: DB_HOST
        fromSecret: DB_HOST
      - key: DB_PORT
        value: "3306"