# Generated by Django 5.2.5 on 2025-10-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mentor_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
