# Generated by Django 4.2 on 2025-02-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlogin',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
