# Generated by Django 5.2.5 on 2025-09-21 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0002_conversation_course_enrollment_lesson_message_module_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_image',
            new_name='course_images',
        ),
    ]
