# Generated by Django 5.2.5 on 2025-10-03 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0003_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='admin_participants',
            field=models.ManyToManyField(blank=True, related_name='admin_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
