# Generated by Django 5.2.5 on 2025-09-22 10:11

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0003_rename_course_image_course_course_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='coursestatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='student',
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='learning_status',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course_code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='mentor_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='merchant_request_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated (STK started)'), ('paid_pending_approval', 'Paid (Pending Mentor Approval)'), ('approved', 'Approved (Accessible to Student)'), ('failed', 'Payment Failed'), ('rejected', 'Rejected by Mentor')], default='initiated', max_length=40),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='TechApp.course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='TechApp.member'),
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='CourseStatus',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
