# Generated by Django 5.2.5 on 2025-09-23 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0004_remove_submission_assignment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
    ]
