# Generated by Django 5.2.5 on 2025-10-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0004_conversation_admin_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_prompt_shown',
            field=models.BooleanField(default=False),
        ),
    ]
