# Generated by Django 4.2 on 2025-02-26 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0005_mentor_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Web Development', 'Web Development'), ('Android Development', 'Android Development'), ('IT Support', 'IT Support'), ('Graphic Design', 'Graphic Design'), ('Cybersecurity', 'Cybersecurity'), ('Advanced Excel', 'Advanced Excel'), ('CCTV Installation', 'CCTV Installation'), ('Project Management System', 'Project Management System'), ('AI', 'AI'), ('Cloud Computing', 'Cloud Computing')], max_length=100)),
                ('course_code', models.CharField(editable=False, max_length=10)),
                ('learning_material', models.FileField(blank=True, help_text='Supported formats: .pdf, .doc, .docx', null=True, upload_to='courses/materials/')),
                ('video', models.FileField(blank=True, null=True, upload_to='courses/videos/')),
                ('zoom_link', models.URLField(blank=True, null=True)),
                ('google_classroom', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Uploaded', 'Uploaded'), ('Enrolled', 'Enrolled'), ('Learning', 'Learning')], default='Uploaded', max_length=20)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechApp.adminlogin')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_status', models.CharField(choices=[('Not Started', 'Not Started'), ('Started', 'Started')], default='Not Started', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechApp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechApp.member')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='member',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mentor',
        ),
        migrations.AlterField(
            model_name='coursestatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_statuses', to='TechApp.member'),
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
