# Generated by Django 5.2.5 on 2025-09-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0006_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='student_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
