# Generated by Django 5.2.5 on 2025-08-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0006_course_enrollment_remove_student_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
