# Generated by Django 5.2.5 on 2025-08-19 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0009_lesson_module_delete_filemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='TechApp.adminlogin'),
        ),
    ]
