# Generated by Django 5.2.5 on 2025-08-20 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0010_alter_course_mentor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='title',
            new_name='subtopic',
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='code1234', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='topic',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='TechApp.course'),
        ),
    ]
