# Generated by Django 5.2.5 on 2025-08-20 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0014_alter_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_title',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='TechApp.course'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('course', 'module_title', 'topic', 'subtopic')},
        ),
    ]
