# Generated by Django 5.2.5 on 2025-08-21 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0015_module_module_title_alter_module_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='module_title',
            new_name='title',
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('course', 'title')},
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='TechApp.module')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('module', 'title')},
            },
        ),
        migrations.RemoveField(
            model_name='module',
            name='subtopic',
        ),
        migrations.RemoveField(
            model_name='module',
            name='topic',
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='TechApp.topic')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('topic', 'title')},
            },
        ),
    ]
