# Generated by Django 5.2.5 on 2025-08-21 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0016_rename_module_title_module_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtopic',
            old_name='title',
            new_name='subtopic',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='title',
            new_name='topic',
        ),
        migrations.AlterUniqueTogether(
            name='subtopic',
            unique_together={('topic', 'subtopic')},
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('module', 'topic')},
        ),
    ]
