# Generated by Django 5.2.5 on 2025-08-21 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0017_rename_title_subtopic_subtopic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtopic',
            old_name='subtopic',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic',
            new_name='title',
        ),
        migrations.AlterUniqueTogether(
            name='subtopic',
            unique_together={('topic', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('module', 'title')},
        ),
    ]
