# Generated by Django 5.2.5 on 2025-08-31 18:32

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0018_rename_subtopic_subtopic_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='resource',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='lesson',
            name='links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='recording',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_type',
            field=models.CharField(choices=[('none', 'None'), ('youtube', 'YouTube'), ('upload', 'Upload')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'title')},
        ),
    ]
