# Generated by Django 5.2.5 on 2025-09-08 15:50

import TechApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0019_rename_resource_lesson_notes_lesson_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlogin',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=TechApp.models.admin_profile_upload_path),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(upload_to=TechApp.models.assignment_upload_path),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='notes',
            field=models.FileField(blank=True, null=True, upload_to=TechApp.models.lesson_notes_upload_path),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='recording',
            field=models.FileField(blank=True, null=True, upload_to=TechApp.models.lesson_recording_upload_path),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=TechApp.models.lesson_video_upload_path),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=TechApp.models.profile_image_upload_path),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_file',
            field=models.FileField(blank=True, null=True, upload_to=TechApp.models.submission_upload_path),
        ),
    ]
