# Generated by Django 5.2.5 on 2025-09-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0023_alter_contact_message_alter_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlogin',
            name='password',
            field=models.CharField(max_length=250),
        ),
    ]
