# Generated by Django 5.2.5 on 2025-09-14 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0024_alter_adminlogin_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('conversation_type', models.CharField(choices=[('dm', 'Direct Message'), ('forum', 'Forum')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_participants', models.ManyToManyField(blank=True, related_name='conversations', to='TechApp.adminlogin')),
                ('participants', models.ManyToManyField(related_name='conversations', to='TechApp.member')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='TechApp.conversation')),
                ('sender_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TechApp.adminlogin')),
                ('sender_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TechApp.member')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
