# Generated by Django 5.2.5 on 2025-09-14 20:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0025_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlogin',
            name='today',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
